### ISSUE TITLE
USER STORY: Client view consultants home (raw)

### ISSUE THREAD

**Issue by troeske** [troeske/Portfolio-Site#23]
As a client I can view the consultants personal info/home page  so that I can check his expertiese, skills, employment history and personal info

------------------------

## Acceptance Criteria
 
I know when I am done when:
1: I can visit the consultants home page
2: I can see personal info, roles, skills, tools, press links and employment history 
3:

------------------------

## Tasks

- [ ] reference wireframes to define basic order of items on the page
- [ ] implement initial html code using bootstrap and own classes as needed
- [ ] verify basic layout against wireframes
